services:
  db:
    image: mariadb:lts
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    env_file:
      - db.env
    networks:  
      - nextcloud_internal
  redis:
    image: redis:alpine
    restart: always
    networks:  
      - nextcloud_internal   
  app:
    build: 
      context: .
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - VIRTUAL_HOST
      - PHP_UPLOAD_LIMIT=81920M
      - APACHE_BODY_LIMIT=85899345920
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - nextcloud_internal   
  cron:
    build: 
      context: .
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
volumes:
  db:
  nextcloud:
  html:
networks:
  proxy-tier:
  nextcloud_internal:
