services:
  db:
    image: mariadb:lts
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    env_file:
      - db.env
  redis:
    image: redis:alpine
    restart: always
  app:
    build: 
      context: .
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - PHP_UPLOAD_LIMIT=81920M
      - APACHE_BODY_LIMIT=85899345920
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default
  cron:
    build: 
      context: .
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "2121:2121"
    volumes:
      - type: bind
        source: ./proxy/Caddyfile
        target: /etc/caddy/Caddyfile
      - caddy_config:/config
    networks:
      - proxy-tier

volumes:
  db:
  nextcloud:
  html:
  caddy_config:
networks:
  proxy-tier:
