services:
  server:
    image: mcr.microsoft.com/mssql/server:2022-latest      
    ports: 
      - "1433:1433"
    volumes:
      - type: bind
        source: ./env/mssql.pem
        target: /etc/ssl/certs/mssql.pem
      - type: bind
        source: ./env/mssql.key
        target: /etc/ssl/private/mssql.key
    environment:
      ACCEPT_EULA: Y
    env_file:
      db.env

  
